before_script:
  - source /opt/casl-tools/gcc-8.3.0/load_dev_env.sh
  - BASE_DIR=/localhome/gitlab-runner
  - ENV_BASE=/opt/casl-tools/gcc-8.3.0
  - which gcc
  - echo $ENV_BASE
  - echo $BASE_DIR

release:
  tags:
    - linux
  variables:
    BLD_NAME: "gnu_release_debug"
    BLD_DIR: "/tmp/$BLD_NAME"
  artifacts:
    paths:
      - LastTestsFailed.log
      - LastTest.log
      - CTestCostData.txt
    expire_in: 1 week
    when: always
  script:
    - which gcc
    - SRC_DIR=`pwd`
    - mkdir -p $BLD_DIR
    - cd $BLD_DIR
    - rm -rf *
    - cmake -DFutility_ENABLE_DBC:BOOL=ON -DCMAKE_Fortran_COMPILER=`which gfortran` -DCMAKE_C_COMPILER=`which gcc` -DCMAKE_CXX_COMPILER=`which g++` $SRC_DIR
    - make -j28 |& tee make.out
    - ctest -j28
    - (exit `grep -B 4 'Unused \(PRIVATE module \)*variable' make.out | grep 'f90' | wc -l`)
    - (exit `grep "Unused parameter" make.out | grep -vc "mpi_"`)
  after_script:
    - SRC_DIR=`pwd`
    - chmod -R a=u $BLD_DIR
    - cd $BLD_DIR
    - cp $BLD_DIR/Testing/Temporary/* $SRC_DIR/

